---
- hosts: all
  gather_facts: true

  tasks:

    - block:
      - name: 'yum update'
        yum: 
          name: '*'
          state: latest

      - name: 'install apps'
        yum:
          name:
            - epel-release
            - yum-utils
            - python3-setuptools
            - bash-completion
            - tmux
            - docker
          state: latest
    

      - name: Start service docker
        service:
          name: docker
          state: started

      - name: enable service docker
        service:
          name: docker
          enabled: yes

      - name: add group docker
        group:
          name: docker
          state: present

      - name: add user to docker group
        user:
          name: "{{ ansible_env.USER }}"
          group: docker
          append: yes
      - name: 'pip update'
        pip:
          name: pip
          state: latest

      - name: 'instal virtualenv'
        pip:
          name: virtualenv
          executable: pip3

      - name: Create Python3-virtual environment folder
        file:
          name: /home/centos/venv
          state: directory

      - name: 'make venv'
        pip:
          virtualenv: /home/centos/venv
          virtualenv_command: /usr/local/bin/virtualenv
          virtualenv_python: python3.6
          requirements: /home/centos/init_settings/requirements.txt

      become: true
  
    - name: 'list dotfiles'
      find:
        paths: '{{ ansible_env.HOME }}/init_settings/dotfiles'
        hidden: yes
      register: file_list
 
    - name: 'make link'
      file:
        src: "{{ item.path }}"
        path: "{{ ansible_env.HOME }}/{{ item.path | basename }}"
        state: link
        force: yes
      with_items: "{{ file_list.files }}"

