---
- hosts: all
  gather_facts: true

  tasks:

    - block:
      - name: 'yum update'
        yum: 
          name: '*'
          state: latest

      - name: 'install apps'
        yum:
          name:
            - epel-release
            - yum-utils
              #            - libselinux-python3
            - python3-devel
            - python3-libs
            - python3-setuptools
            - bash-completion
            - tmux
            - docker
          state: latest
    

      - name: Start service docker
        service:
          name: docker
          state: started

      - name: enable service docker
        service:
          name: docker
          enabled: yes

      - name: add group docker
        group:
          name: docker
          state: present

      - name: add user to docker group
        user:
          name: "{{ ansible_env.USER }}"
          group: docker
          append: yes

      become: true
    - block:
      - name: 'pip update'
        pip:
          name: pip
          state: latest

      - name: 'instal virtualenv'
        pip:
          name: virtualenv
          executable: pip3

      - name: Create Python3-virtual environment folder
        file:
          name: "{{ ansible_env.HOME }}/venv"
          state: directory

      - name: 'make venv'
        pip:
          virtualenv: "{{ ansible_env.HOME }}/venv"
          virtualenv_command: /usr/local/bin/virtualenv
          virtualenv_python: python3.7
          requirements: "{{ ansible_env.HOME }}/init_settings_02/requirements.txt"
      vars:
        ansible_python_interpreter: /usr/bin/python3
      become: true
  
    - name: 'list dotfiles'
      find:
        paths: '{{ ansible_env.HOME }}/init_settings_02/dotfiles'
        hidden: yes
      register: file_list
 
    - name: 'make link'
      file:
        src: "{{ item.path }}"
        path: "{{ ansible_env.HOME }}/{{ item.path | basename }}"
        state: link
        force: yes
      with_items: "{{ file_list.files }}"

